### ISSUE TITLE
Unreachable code in der_enter()

### ISSUE THREAD

**Issue by adriaandegroot** [vanrein/quick-der#19]
lib/der_skipenter.c contains der_enter(), with unreachable code at the end of der_enter(). The if(tag == DER_TAG_BITSTRING) is not reached because of the returns in the if-else above it. The comment for the function explicitly mentions this special behavior, as does the comment in test/certio.c, so it might be important behavior. I can't think of a reason to enter a bit-string.

**Comment by vanrein** [comment]
Thanks, you are correct.

This code has not been tested, I imagine.  BIT STRING values are fairly rarely used.  Although they are part of X.509 certificates, for the `signatureValue` and `subjectPublicKey` fields; the `test/certio.c` program didn't pickup on this because it uses the `der_unpack()` method instead.

So, thanks for reporting this before this bug bothered someone.  ASN.1 is used in space flight, you know ;-)
![iur](https://paxarcana.files.wordpress.com/2009/10/moon_rocket.jpg)

**Comment by vanrein** [comment]
Fixed in 067ca2bb00e95086bfd1e335c1d2e7b4283dd301.
