### ISSUE TITLE
Python packaging not flawless

### ISSUE THREAD

**Issue by vanrein** [vanrein/quick-der#32]
The Python packaging code does a few things funnily [though I'm not laughing about it]:

  * The installation in the build directory does not introduce the `quick_der` packaging dir, so setting of `PYTHON_PATH` does not really work
  * This has led to scripts in `test/*.py` that make funny assumptions about package names (they strip the `quick_der` package name)
  * The generated scripts do not end up in `python/quick_der/*.py` where they ought to be
  * The `__init__.py` and `api.py` are not installed alongside the generated scripts
  * The `setup.py` file does not incorporate these files; we only seem to build and install `_quickder.so` with it and leave the rest to CMake

**Comment by adriaandegroot** [comment]
I think these have all been fixed by commits on-or-before ea64da2 .

But does the filesystem hierarchy constructed in the build-directory matter, as long as the tests can run and the Python bindings work once installed? I wouldn't call those breaking issues.

There's one remaining issue where setup.py knows about things that need to be installed, but cmake doesn't -- so all the quick_der/rfc*.py and similar bindings files are installed, but not handled by cpack.

**Comment by vanrein** [comment]
Yes, these have now been solved.  We can close the issue; thanks for pointing that out.
