### ISSUE TITLE
asn2quickder python script doesn't work when installed

### ISSUE THREAD

**Issue by gijzelaerr** [vanrein/quick-der#36]
the ans1ate module is not installed

```
 python2.7 /usr/local/bin/asn2quickder
Traceback (most recent call last):
  File "/usr/local/bin/asn2quickder", line 34, in <module>
    from asn1ate import parser
ImportError: No module named asn1ate
```

**Comment by adriaandegroot** [comment]
There is a packaged version of asn1ate, which can be installed with *pip* or *easy_install*. It may even have Debian packages already. **But** it won't work, since it's too old and doesn't contain a number of patches applied locally. I have a local branch that renames the tool and tries to install it as well.
