### ISSUE TITLE
On OS X shared libraries have .dylib extension 

### ISSUE THREAD

**Issue by gijzelaerr** [vanrein/quick-der#57]
https://github.com/vanrein/quick-der/blob/master/contrib/cmake/Quick-DERConfig.cmake.in#L12

**Comment by vanrein** [comment]
Thank you Gijs.  This also applies to Windows of course.

Since your platform needs it, you're in an excellent position to modify and test without further interaction... would you mind?

The phrases to use would be the macros [CMAKE_SHARED_LIBRARY_SUFFIX](https://cmake.org/cmake/help/v3.0/variable/CMAKE_SHARED_LIBRARY_SUFFIX.html) and [CMAKE_STATIC_LIBRARY_SUFFIX](https://cmake.org/cmake/help/v3.0/variable/CMAKE_STATIC_LIBRARY_SUFFIX.html)

**Comment by vanrein** [comment]
solved by Gijs
